import type { VocabularyItem } from "@le/core";

export const deVocabulary: VocabularyItem[] = [
  { lemma: "gehen", pos: "verb", minimumLevel: "A1" },
  { lemma: "Freund", pos: "noun", minimumLevel: "A1" },
  { lemma: "Geschenk", pos: "noun", minimumLevel: "A1" },
  { lemma: "Bruder", pos: "noun", minimumLevel: "A1" },
  { lemma: "sehen", pos: "verb", minimumLevel: "A1" },
  { lemma: "Hund", pos: "noun", minimumLevel: "A1" },
  { lemma: "helfen", pos: "verb", minimumLevel: "A1" },
  { lemma: "Kind", pos: "noun", minimumLevel: "A1" },
  { lemma: "klein", pos: "adj", minimumLevel: "A1" },
  { lemma: "schlafen", pos: "verb", minimumLevel: "A1" },
  { lemma: "lernen", pos: "verb", minimumLevel: "A1" },
  { lemma: "aufstehen", pos: "verb", minimumLevel: "A1" },
  { lemma: "Uhr", pos: "noun", minimumLevel: "A1" },
  { lemma: "sprechen", pos: "verb", minimumLevel: "A2" },
  { lemma: "Projekt", pos: "noun", minimumLevel: "A2" },
  { lemma: "spielen", pos: "verb", minimumLevel: "A2" },
  { lemma: "fahren", pos: "verb", minimumLevel: "A2" },
  { lemma: "Bus", pos: "noun", minimumLevel: "A2" },
  { lemma: "Plan", pos: "noun", minimumLevel: "A2" },
  { lemma: "diskutieren", pos: "verb", minimumLevel: "B1" },
  { lemma: "Chef", pos: "noun", minimumLevel: "B1" },
  { lemma: "kaempfen", pos: "verb", minimumLevel: "B1" },
  { lemma: "Erfolg", pos: "noun", minimumLevel: "B1" },
  { lemma: "vertrauen", pos: "verb", minimumLevel: "B1" },
  { lemma: "Arzt", pos: "noun", minimumLevel: "B1" },
  { lemma: "anmelden", pos: "verb", minimumLevel: "B1" },
  { lemma: "morgen", pos: "adv", minimumLevel: "B1" },
  { lemma: "arbeiten", pos: "verb", minimumLevel: "B1" },
  { lemma: "erfahren", pos: "adj", minimumLevel: "B2" },
  { lemma: "Lehrer", pos: "noun", minimumLevel: "B2" },
  { lemma: "erklaeren", pos: "verb", minimumLevel: "B2" },
  { lemma: "Problem", pos: "noun", minimumLevel: "B2" },
  { lemma: "loesen", pos: "verb", minimumLevel: "B2" },
  { lemma: "besuchen", pos: "verb", minimumLevel: "B2" },
  { lemma: "Kunde", pos: "noun", minimumLevel: "B2" },
  { lemma: "wissenschaftlich", pos: "adj", minimumLevel: "C1" },
  { lemma: "Bericht", pos: "noun", minimumLevel: "C1" },
  { lemma: "fertig", pos: "adj", minimumLevel: "C1" },
  { lemma: "verantwortlich", pos: "adj", minimumLevel: "C1" },
  { lemma: "Manager", pos: "noun", minimumLevel: "C1" }
];
